///////////////////////////////////////
//Daniel Truong
//CSE 002
//October 14, 2014
//
//  In this program, user will be given a permanent number 
//  that he or she will be betting on for every Roulette spin.
//  First the user will play 100 spins of Roulette. If user wins 3 or more spins,
//  he wins profit. If user wins 1 or 2 spins, he gets money but not enough
//  to break even. If user does not win a spin, he receives no money. 
//  This program will run the 100 spin game 1000 and out put the amount of times
//  the user makes profit, makes some money, or receives no money per 100 spins. 
//
//  first compile the program javac Roulette.java
//  then run the program java Roulette
import java.util.Random; //importing random generator
//define a class
public class Roulette {
//main method required for every program
  public static void main(String[] args) {

    Random generator = new Random();
    int randomNumber = generator.nextInt(38)+1; //This will automatically assign a number between 1 and 38 user will use in Roulette
    int win; 
    int loss = 0;
    int winGame = 0;
    int lossGame = 0;
    int profit = 0;
    int bankrupt = 0;
    int netLoss = 0;
    int randomRoulette;
    int totalWins = 0;
    //variable declaration 
    for (int i = 0; i < 1000; i++) { //This for loop will run the 100 spin game 1000 times 
      win = 0; //This assigment assures that the wins will always reset after every 100 spins in Roulette so we can keep track of wins and losses separately
      for (int n=0; n<100; n++) { //Loop will run 100 Roulette spins
        randomRoulette = generator.nextInt(38)+1; //This gives the number generated by the Roulette spin
          if (randomRoulette == randomNumber) {
            win++; //If the roulette lands on your number, you win!
            totalWins++;
          }
      }
               if (win >= 3) {
                 profit++; //Must win at least 3 spins out of 100 to make profit
               }
               else if (win == 1 || win == 2) {
                 netLoss++; //Makes money, but doesn't break even
               }
               else if (win == 0) {
                 bankrupt++; //User does not win one spin
               }
    } 
    System.out.println("The number on the Roulette wheel you are betting on is " +randomNumber); //outputs permanent number user is betting in roulette
    System.out.println("You won profit in " +profit+ " games."); //This is the amount of games out of 1000 where user makes profit in 100 spins
    System.out.println("You won money but did not break even in " +netLoss+ " games."); //This it the amount of games out of 1000 where user wins only 1 or 2 spins, making some money but not brekaing even
    System.out.println("You lost all your money in " +bankrupt+ " games."); //Number of games out of 1000 where user does not win money in 100 spins
    System.out.println("You won a total of " +totalWins+ " spins.");
    System.out.println("The total winnings you walked out with is $" +(totalWins*36));
  } //end of main
} //end of class